Assignment_2/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment_2.Models
{
    public class Trainer
    {
        public int? Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Subject { get; set; }
    }
}

Assignment_2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Assignment_2/Controllers/TrainerController.cs
using Assignment_2.MyContext;
using Assignment_2.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment_2.Models;


namespace Assignment_2.Controllers
{
    public class TrainerController : Controller
    {
        private ApllicationContext db = new ApllicationContext();

        private TrainerRepository trainerRepository;

        public TrainerController()
        {
            trainerRepository = new TrainerRepository(db);
        }

        
        public ActionResult Index()
        {   
            var trainers = trainerRepository.GetAll();

            return View(trainers);
        }

        public ActionResult Details(int? Id)
        {
            var trainer = trainerRepository.GetById(Id);
            if (trainer == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            
            return View(trainer);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Trainer trainer)  
        {   
            if (ModelState.IsValid)               
            {
                trainerRepository.Add(trainer);
                TempData["message"] = "You have succesfully created trainer " + trainer.FirstName;
                return RedirectToAction("Index");
            }

            return View(trainer);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var emp = trainerRepository.GetById(id);

            if (emp == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(emp);
        }

        [HttpPost]
        public ActionResult Edit(Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                trainerRepository.Edit(trainer);
                TempData["message"] = $"Employee with id {trainer.Id} Successfully Modified";
                
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            var trainer = trainerRepository.GetById(id);
            if (trainer == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            trainerRepository.Delete(trainer);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }

    }
}

Assignment_2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assignment_2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assignment_2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Assignment 2";
}

<h1>Assignment 2</h1>

Assignment_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Assignment 2", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trainers", "Index", "Trainer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Assignment_2/Views/Trainer/Create.cshtml
@model Assignment_2.Models.Trainer

@using Assignment_2.Models


<h1>Create New Trainer</h1>

<form method="post">

    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Give your First Name" } })
        @Html.ValidationMessageFor(m => m.FirstName, "", new { title = "Boom", id = "boomer", @class = "text-danger" })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Give The Last Name" } })
        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.Subject)
        @Html.EditorFor(m => m.Subject, new { htmlAttributes = new { @class = "form-control", placeholder = "Give The Subject" } })
        @Html.ValidationMessageFor(m => m.Subject, "", new { @class = "text-danger" })
    </div>


    <input class="btn btn-primary" type="submit" value="Create" />
    <input class="btn btn-success" type="reset" value="Clear" />
</form>


@Html.ActionLink("Go Back", "Index", null, new { @class = "btn btn-success" });

Assignment_2/Views/Trainer/Details.cshtml
@model Assignment_2.Models.Trainer

@using Assignment_2.Models

@{
    ViewBag.Title = "Details";
}


<br />
<strong>First Name:</strong>
<span>@Model.FirstName</span>
<br />
<strong>Last Name:</strong>
<span>@Model.LastName</span>
<br />
<strong>Subject:</strong>
<span>@Model.Subject</span>
<br />
<a href="/Trainer/Index">Go Back</a>

Assignment_2/Views/Trainer/Edit.cshtml
@model Assignment_2.Models.Trainer

@using Assignment_2.Models

<h1>Edit Trainer</h1>

<form method="post">

    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(m => m.FirstName, "", new { title = "Boom", id = "boomer", @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Type the Salary" } })
        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Subject)
        @Html.EditorFor(m => m.Subject, new { htmlAttributes = new { @class = "form-control", placeholder = "Type the Age" } })
        @Html.ValidationMessageFor(m => m.Subject, "", new { @class = "text-danger" })
    </div>


    <input class="btn btn-primary" type="submit" value="Update" />
    <input class="btn btn-success" type="reset" value="Clear" />
</form>

Assignment_2/Views/Trainer/Index.cshtml
@model IEnumerable<Assignment_2.Models.Trainer>

@using Assignment_2.Models




@if (TempData["message"] != null)
{
    <div class="alert alert-success alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["message"]
    </div>
}

<a class="btn btn-primary" href="/Trainer/Create">Create Trainer</a>

<br />

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Subject</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var t in Model)
        {
            <tr>
                <td>@t.Id</td>
                <td>@t.FirstName</td>
                <td>@t.LastName</td>
                <td>@t.Subject</td>

                <td>
                    <a class="btn btn-primary" href="/Trainer/Details?id=@t.Id">Details</a>
                    <a class="btn btn-success" href="/Trainer/Edit?id=@t.Id">Edit</a>


                    <form class="text-warning" action="/trainer/delete" method="post">

                        <input type="hidden" name="id" value="@t.Id" />
                        <input type="submit" value="Delete" />

                    </form>
                </td>
            </tr>
        }

    </tbody>

</table>